# GENERATED by scripts/unasync.py from _async/client.py -- do not edit.
"""Synchronous client (generated from ``_async/client.py``)."""

from __future__ import annotations

import builtins
from collections.abc import Iterator, Callable, Mapping
from types import TracebackType
from typing import IO, Any, TypeVar

import httpx

from .. import _operations as ops
from .._pagination import DEFAULT_PAGE_SIZE, options_for_page
from .._transport import (
    JSON,
    UNSET,
    Operation,
    Response,
    build_request,
    default_headers,
    to_response,
)
from .._transport import base_url as api_base_url
from ..errors import NetworkError
from ..models.auth import PingResponse, TokenResponse
from ..models.circularity_hub import AddObjectEntry, CircularityHubOrder, FilterObject
from ..models.enums import AssetTrackingTemplate, SSOAppTarget, SSOProviderName, TaskStatus
from ..models.field_definitions import (
    SYSTEM_MANAGED_FIELD_KEYS,
    CreateFieldDefinition,
    FieldDefinition,
    UpdateFieldDefinition,
)
from ..models.fields import Fields
from ..models.files import File, FileAttachment
from ..models.history import (
    HistoryResponse,
    LocationHistoryEntry,
    ObjectHistoryEntry,
    PersonHistoryEntry,
    RentalCaseHistoryEntry,
    RoomHistoryEntry,
    TaskHistoryEntry,
)
from ..models.list_options import (
    HistoryListOptions,
    ListOptions,
    PersonListOptions,
    TaskListOptions,
    UserListOptions,
)
from ..models.persons import Person, PersonListResponse
from ..models.rentals import CreateRentalCase, RentalCase, UpdateRentalCase
from ..models.reports import CreateReport, ReportTemplate
from ..models.tasks import CreateTask, Task, UpdateTask
from ..models.users import User, UserListResponse

T = TypeVar("T")

DEFAULT_TIMEOUT = 30.0


def _walk(fetch: Callable[[int], builtins.list[T]], per_page: int) -> Iterator[T]:
    """Yield items page by page, stopping after the first short (or empty) page."""
    page = 1
    while True:
        items = fetch(page)
        for item in items:
            yield item
        if len(items) < per_page:
            return
        page += 1


class Client:
    """Synchronous client for the seventhings Customer API.

    ``base_url`` is the instance URL, e.g. ``https://example.seventhings.com``.
    Pass ``http_client`` to use your own ``httpx.Client`` (it is not closed
    by this client); otherwise one is created with the given ``timeout``.
    """

    def __init__(
        self,
        base_url: str,
        *,
        token: str | None = None,
        client_id: str | None = None,
        http_client: httpx.Client | None = None,
        timeout: float | httpx.Timeout | None = DEFAULT_TIMEOUT,
    ) -> None:
        self._base_url = api_base_url(base_url)
        self.token = token
        self.client_id = client_id
        self._owns_http = http_client is None
        self._http = http_client or httpx.Client(timeout=timeout, headers=default_headers())

        self.auth = AuthService(self)
        self.objects = ObjectsService(self)
        self.rooms = RoomsService(self)
        self.locations = LocationsService(self)
        self.users = UsersService(self)
        self.persons = PersonsService(self)
        self.files = FilesService(self)
        self.tasks = TasksService(self)
        self.rentals = RentalsService(self)
        self.field_definitions = FieldDefinitionsService(self)
        self.circularity_hub = CircularityHubService(self)
        self.reports = ReportsService(self)

    @classmethod
    def with_credentials(
        cls,
        base_url: str,
        username: str,
        password: str,
        client_id: str,
        *,
        http_client: httpx.Client | None = None,
        timeout: float | httpx.Timeout | None = DEFAULT_TIMEOUT,
    ) -> Client:
        """Create a client and log in with username/password."""
        client = cls(base_url, http_client=http_client, timeout=timeout)
        try:
            client.auth.login(username, password, client_id)
        except BaseException:
            client.close()
            raise
        return client

    @property
    def base_url(self) -> str:
        """API base URL (instance URL + ``/customer-api/v1``)."""
        return self._base_url

    def close(self) -> None:
        if self._owns_http:
            self._http.close()

    def __enter__(self) -> Client:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        self.close()

    def _send(self, op: Operation[T]) -> T:
        request = build_request(self._http, self._base_url, self.token, op)
        try:
            resp = self._http.send(request)
        except httpx.TransportError as exc:
            raise NetworkError(str(exc) or type(exc).__name__) from exc
        return op.parse(to_response(resp))

    def request(
        self,
        method: str,
        path: str,
        *,
        query: str = "",
        json: Any = UNSET,
        accept: str | None = JSON,
        authenticated: bool = True,
    ) -> Response:
        """Low-level escape hatch: perform a request relative to the API base URL.

        Raises APIError for status >= 400.
        """
        return self._send(
            ops.raw(
                method, path, query=query, json=json, accept=accept, authenticated=authenticated
            )
        )

    def ping(self) -> PingResponse:
        """Call the unauthenticated root endpoint."""
        return self._send(ops.ping())


class _Service:
    def __init__(self, client: Client) -> None:
        self._client = client

    def _send(self, op: Operation[T]) -> T:
        return self._client._send(op)


class AuthService(_Service):
    """Token endpoints. Successful logins store the access token on the client."""

    def _store(self, op: Operation[TokenResponse]) -> TokenResponse:
        token = self._send(op)
        self._client.token = token.access_token
        return token

    def login(self, username: str, password: str, client_id: str) -> TokenResponse:
        self._client.client_id = client_id
        return self._store(ops.login(username, password, client_id))

    def login_sso(
        self,
        provider: SSOProviderName | str,
        auth_code: str,
        client_id: str,
        app_target: SSOAppTarget | str | None = None,
    ) -> TokenResponse:
        self._client.client_id = client_id
        return self._store(ops.login_sso(provider, auth_code, client_id, app_target))

    def refresh(self, refresh_token: str) -> TokenResponse:
        """Exchange a refresh token, using the client ID from the last login."""
        return self._store(ops.refresh(refresh_token, self._client.client_id or ""))

    def revoke_tokens(self) -> None:
        """Revoke the current tokens server-side (the local token is kept)."""
        self._send(ops.revoke_tokens())


class ObjectsService(_Service):
    """Objects (assets). Records are schema-free field maps."""

    def list(self, opts: ListOptions | None = None) -> builtins.list[dict[str, Any]]:
        return self._send(ops.resource_list("objects", opts, unwrap=False))

    def all(self, opts: ListOptions | None = None) -> Iterator[Fields]:
        """Iterate every object across all pages (``opts.page`` is ignored)."""

        def fetch(page: int) -> builtins.list[dict[str, Any]]:
            return self.list(options_for_page(opts, ListOptions, page))

        for item in _walk(fetch, _per_page(opts)):
            yield Fields(item)

    def count(self, opts: ListOptions | None = None) -> int:
        return self._send(ops.resource_count("objects", opts))

    def create(self, fields: Mapping[str, Any]) -> str:
        """Create an object and return its UUID."""
        return self._send(ops.resource_create("object", fields))

    def get(self, uuid: str) -> dict[str, Any]:
        return self._send(ops.resource_get("object", uuid, unwrap=False))

    def get_by_barcode(self, barcode: str) -> dict[str, Any]:
        """Look up an object by barcode (archived objects included)."""
        return self._send(ops.object_get_by_barcode(barcode))

    def patch(self, uuid: str, fields: Mapping[str, Any]) -> None:
        self._send(ops.resource_patch("object", uuid, fields))

    def delete(self, uuid: str) -> None:
        self._send(ops.resource_delete("object", uuid))

    def archive(self, uuid: str) -> None:
        self._send(ops.object_archive(uuid, archive=True))

    def unarchive(self, uuid: str) -> None:
        self._send(ops.object_archive(uuid, archive=False))

    def add_files(self, uuid: str, attachments: builtins.list[FileAttachment]) -> Response:
        """Attach uploaded files; the raw response may be 200 or 207 (multi-status)."""
        return self._send(ops.object_files(uuid, attachments, add=True))

    def remove_files(self, uuid: str, attachments: builtins.list[FileAttachment]) -> Response:
        return self._send(ops.object_files(uuid, attachments, add=False))

    def history(
        self, uuid: str, opts: HistoryListOptions | None = None
    ) -> HistoryResponse[ObjectHistoryEntry]:
        return self._send(ops.object_history(uuid, opts))


class _SpaceService(_Service):
    """Rooms and locations share one shape; ``{uuid, fields}`` envelopes are flattened."""

    _plural: str
    _singular: str

    def list(self, opts: ListOptions | None = None) -> builtins.list[dict[str, Any]]:
        return self._send(ops.resource_list(self._plural, opts, unwrap=True))

    def all(self, opts: ListOptions | None = None) -> Iterator[Fields]:
        """Iterate every record across all pages (``opts.page`` is ignored)."""

        def fetch(page: int) -> builtins.list[dict[str, Any]]:
            return self.list(options_for_page(opts, ListOptions, page))

        for item in _walk(fetch, _per_page(opts)):
            yield Fields(item)

    def count(self, opts: ListOptions | None = None) -> int:
        return self._send(ops.resource_count(self._plural, opts))

    def create(self, fields: Mapping[str, Any]) -> str:
        """Create a record and return its UUID."""
        return self._send(ops.resource_create(self._singular, fields))

    def get(self, uuid: str) -> dict[str, Any]:
        return self._send(ops.resource_get(self._singular, uuid, unwrap=True))

    def patch(self, uuid: str, fields: Mapping[str, Any]) -> dict[str, Any] | None:
        """Update fields; returns the updated record, or None if the API sent no body."""
        return self._send(ops.resource_patch_unwrapped(self._singular, uuid, fields))

    def delete(self, uuid: str) -> None:
        self._send(ops.resource_delete(self._singular, uuid))


class RoomsService(_SpaceService):
    _plural = "rooms"
    _singular = "room"

    def history(
        self, uuid: str, opts: HistoryListOptions | None = None
    ) -> HistoryResponse[RoomHistoryEntry]:
        return self._send(ops.room_history(uuid, opts))


class LocationsService(_SpaceService):
    _plural = "locations"
    _singular = "location"

    def history(
        self, uuid: str, opts: HistoryListOptions | None = None
    ) -> HistoryResponse[LocationHistoryEntry]:
        return self._send(ops.location_history(uuid, opts))


class UsersService(_Service):
    def list(self, opts: UserListOptions | None = None) -> UserListResponse:
        return self._send(ops.users_list(opts))

    def all(self, opts: UserListOptions | None = None) -> Iterator[User]:
        """Iterate every user across all pages (``opts.page`` is ignored)."""

        def fetch(page: int) -> builtins.list[User]:
            return (self.list(options_for_page(opts, UserListOptions, page))).items

        for user in _walk(fetch, _per_page(opts)):
            yield user

    def get(self, uuid: str) -> User:
        return self._send(ops.user_get(uuid))

    def get_by_id(self, user_id: int) -> User:
        return self._send(ops.user_get_by_id(user_id))


class PersonsService(_Service):
    def list(self, opts: PersonListOptions | None = None) -> PersonListResponse:
        return self._send(ops.persons_list(opts))

    def all(self, opts: PersonListOptions | None = None) -> Iterator[Person]:
        """Iterate every person across all pages (``opts.page`` is ignored)."""

        def fetch(page: int) -> builtins.list[Person]:
            return (self.list(options_for_page(opts, PersonListOptions, page))).items

        for person in _walk(fetch, _per_page(opts)):
            yield person

    def count(self, opts: PersonListOptions | None = None) -> int:
        return self._send(ops.persons_count(opts))

    def get(self, uuid: str) -> Person:
        return self._send(ops.person_get(uuid))

    def get_by_id(self, person_id: int) -> Person:
        return self._send(ops.person_get_by_id(person_id))

    def create(self, fields: Mapping[str, Any]) -> str:
        """Create a person and return its UUID."""
        return self._send(ops.person_create(fields))

    def patch(self, uuid: str, fields: Mapping[str, Any]) -> None:
        self._send(ops.resource_patch("person", uuid, fields))

    def delete(self, uuid: str) -> None:
        self._send(ops.resource_delete("person", uuid))

    def create_user(self, filter: FilterObject) -> None:
        """Create user accounts for the persons matching ``filter.filter`` (sort is ignored)."""
        self._send(ops.person_create_user(filter))

    def history(
        self, uuid: str, opts: HistoryListOptions | None = None
    ) -> HistoryResponse[PersonHistoryEntry]:
        return self._send(ops.person_history(uuid, opts))


class FilesService(_Service):
    def list(self) -> builtins.list[File]:
        """The most recent files (the API returns at most 20; no paging)."""
        return self._send(ops.files_list())

    def get(self, uuid: str) -> File:
        return self._send(ops.file_get(uuid))

    def upload(self, filename: str, data: bytes | IO[bytes]) -> str:
        """Upload a file (multipart field ``data``) and return its UUID."""
        return self._send(ops.file_upload(filename, data))

    def get_data(self, uuid: str) -> bytes:
        return self._send(ops.file_data(uuid, thumbnail=False))

    def get_thumbnail(self, uuid: str) -> bytes:
        return self._send(ops.file_data(uuid, thumbnail=True))


class TasksService(_Service):
    def list(self, opts: TaskListOptions | None = None) -> builtins.list[Task]:
        return self._send(ops.tasks_list(opts))

    def get(self, uuid: str) -> Task:
        return self._send(ops.task_get(uuid))

    def create(self, task: CreateTask) -> str:
        """Create a task and return its UUID."""
        return self._send(ops.task_create(task))

    def update(self, uuid: str, task: UpdateTask) -> None:
        """Replace a task (PUT)."""
        self._send(ops.task_update(uuid, task))

    def delete(self, uuid: str) -> None:
        self._send(ops.task_delete(uuid))

    def update_status(self, uuid: str, status: TaskStatus | str) -> None:
        self._send(ops.task_update_status(uuid, status))

    def history(
        self, uuid: str, opts: HistoryListOptions | None = None
    ) -> HistoryResponse[TaskHistoryEntry]:
        return self._send(ops.task_history(uuid, opts))


class RentalsService(_Service):
    def list(self, opts: ListOptions | None = None) -> builtins.list[RentalCase]:
        return self._send(ops.rentals_list(opts))

    def all(self, opts: ListOptions | None = None) -> Iterator[RentalCase]:
        """Iterate every rental case across all pages (``opts.page`` is ignored)."""

        def fetch(page: int) -> builtins.list[RentalCase]:
            return self.list(options_for_page(opts, ListOptions, page))

        for rental in _walk(fetch, _per_page(opts)):
            yield rental

    def get(self, uuid: str) -> RentalCase:
        return self._send(ops.rental_get(uuid))

    def create(self, rental: CreateRentalCase) -> str:
        """Create a rental case and return its UUID."""
        return self._send(ops.rental_create(rental))

    def update(self, uuid: str, rental: UpdateRentalCase) -> None:
        """Replace a rental case (PUT)."""
        self._send(ops.rental_update(uuid, rental))

    def delete(self, uuid: str) -> None:
        self._send(ops.rental_delete(uuid))

    def history(
        self, uuid: str, opts: HistoryListOptions | None = None
    ) -> HistoryResponse[RentalCaseHistoryEntry]:
        return self._send(ops.rental_history(uuid, opts))


class FieldDefinitionsService(_Service):
    def list(self, template: AssetTrackingTemplate | str) -> builtins.list[FieldDefinition]:
        return self._send(ops.field_definitions_list(template))

    def get(self, template: AssetTrackingTemplate | str, uuid: str) -> FieldDefinition:
        return self._send(ops.field_definition_get(template, uuid))

    def create(
        self, template: AssetTrackingTemplate | str, definition: CreateFieldDefinition
    ) -> str:
        """Create a field definition and return its UUID."""
        return self._send(ops.field_definition_create(template, definition))

    def update(
        self,
        template: AssetTrackingTemplate | str,
        uuid: str,
        definition: UpdateFieldDefinition,
    ) -> None:
        self._send(ops.field_definition_update(template, uuid, definition))

    def mandatory(self, template: AssetTrackingTemplate | str) -> builtins.list[FieldDefinition]:
        """Definitions callers must fill in (mandatory and not system-managed)."""
        return [
            d
            for d in self.list(template)
            if d.is_mandatory() and d.field_key not in SYSTEM_MANAGED_FIELD_KEYS
        ]

    def missing_mandatory_fields(
        self, template: AssetTrackingTemplate | str, fields: Mapping[str, Any]
    ) -> builtins.list[str]:
        """Keys of mandatory fields that are absent or null in ``fields``."""
        return [d.field_key for d in self.mandatory(template) if fields.get(d.field_key) is None]


class CircularityHubService(_Service):
    """Circularity Hub. Items and orders use integer IDs, not UUIDs."""

    def suggest_category(self, filter: FilterObject) -> dict[str, str] | None:
        """Category suggestions, or None when the API has none."""
        return self._send(ops.hub_suggest_category(filter))

    def suggest_rest_price(self, values: Mapping[str, str]) -> dict[str, str] | None:
        """Rest-price suggestions, or None when the API has none."""
        return self._send(ops.hub_suggest_rest_price(values))

    def add_objects(self, entries: Mapping[str, AddObjectEntry]) -> None:
        """Add objects (keyed by object UUID) to the hub."""
        self._send(ops.hub_add_objects(entries))

    def list_items(self, opts: ListOptions | None = None) -> builtins.list[dict[str, Any]]:
        return self._send(ops.hub_items_list(opts))

    def all_items(self, opts: ListOptions | None = None) -> Iterator[Fields]:
        """Iterate every hub item across all pages (``opts.page`` is ignored)."""

        def fetch(page: int) -> builtins.list[dict[str, Any]]:
            return self.list_items(options_for_page(opts, ListOptions, page))

        for item in _walk(fetch, _per_page(opts)):
            yield Fields(item)

    def get_item(self, item_id: int) -> dict[str, Any]:
        return self._send(ops.hub_item_get(item_id))

    def update_item(self, item_id: int, fields: Mapping[str, Any]) -> None:
        self._send(ops.hub_item_update(item_id, fields))

    def delete_item(self, item_id: int) -> None:
        self._send(ops.hub_item_delete(item_id))

    def list_orders(self, opts: ListOptions | None = None) -> builtins.list[CircularityHubOrder]:
        return self._send(ops.hub_orders_list(opts))

    def create_order(self, item_ids: builtins.list[int]) -> int:
        """Create an order for the given item IDs and return the order ID."""
        return self._send(ops.hub_order_create(item_ids))

    def get_order(self, order_id: int) -> CircularityHubOrder:
        return self._send(ops.hub_order_get(order_id))

    def update_order(self, order_id: int, fields: Mapping[str, Any]) -> None:
        self._send(ops.hub_order_update(order_id, fields))


class ReportsService(_Service):
    def list_templates(self) -> builtins.list[ReportTemplate]:
        return self._send(ops.report_templates_list())

    def create(self, report: CreateReport) -> bytes:
        """Render a report and return the PDF bytes."""
        return self._send(ops.report_create(report))


def _per_page(opts: ListOptions | UserListOptions | PersonListOptions | None) -> int:
    return (opts.per_page if opts is not None else None) or DEFAULT_PAGE_SIZE
