"""Generate the synchronous client from the asynchronous source.

python scripts/unasync.py          # rewrite src/seventhings/_sync/client.py
python scripts/unasync.py --check  # exit 1 if the generated file is stale
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src/seventhings/_async/client.py"
TARGET = ROOT / "src/seventhings/_sync/client.py"

HEADER = "# GENERATED by scripts/unasync.py from _async/client.py -- do not edit.\n"

# Order matters: specific rewrites first, then the generic ones.
REPLACEMENTS: list[tuple[str, str]] = [
    (r"Awaitable\[builtins\.list\[T\]\]", "builtins.list[T]"),
    (r", Awaitable,", ","),
    (r"\bAsyncIterator\b", "Iterator"),
    (r"\bhttpx\.AsyncClient\b", "httpx.Client"),
    (r"\bAsync(?=[A-Z_])", ""),
    (r"\b_Async(?=[A-Z])", "_"),
    (r"\basync def\b", "def"),
    (r"\basync for\b", "for"),
    (r"\basync with\b", "with"),
    (r"\bawait\s+", ""),
    (r"\baclose\b", "close"),
    (r"__aenter__", "__enter__"),
    (r"__aexit__", "__exit__"),
    (r"\bAsynchronous client\b", "Synchronous client"),
]


def unasync(source: str) -> str:
    out = source
    for pattern, repl in REPLACEMENTS:
        out = re.sub(pattern, repl, out)
    # The module docstring describes the async file; replace it.
    out = re.sub(
        r'^""".*?"""\n',
        '"""Synchronous client (generated from ``_async/client.py``)."""\n',
        out,
        count=1,
        flags=re.S,
    )
    return _format(HEADER + out)


def _format(code: str) -> str:
    """Run ruff format so the generated file is lint-clean."""
    result = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", str(TARGET), "-"],
        input=code,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def main() -> int:
    generated = unasync(SOURCE.read_text())
    if "--check" in sys.argv[1:]:
        if not TARGET.exists() or TARGET.read_text() != generated:
            print(f"{TARGET.relative_to(ROOT)} is stale; run: python scripts/unasync.py")
            return 1
        return 0
    TARGET.write_text(generated)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
